version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    macos:
      xcode: "13.2.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: dev
      ANDROID_SDK_ROOT: '/home/circleci/android-sdk'
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: 
          name: Yarn Install
          command: |
            cd CIReactNativeDemo
            yarn install
      - run: 
          name: Install Gem Android
          command: |
            cd CIReactNativeDemo/android
            bundle install
      - run:
          name: Dependency android
          command: |
            cd CIReactNativeDemo/android
            echo "sdk.dir=/home/circleci/android-sdk" | tee local.properties
            ./gradlew dependencies
      - run:
          name: Fastlane
          command: |
            cd CIReactNativeDemo/android
            bundle exec fastlane dev
