version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    macos:
      xcode: "13.2.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: dev
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: fastlane
          command: |
            cd CIReactNativeDemo
            yarn install
            cd android
            bundle install
            bundle exec fastlane dev
